In [1]:
import os
from datetime import datetime

# Read data and make team, assign players
1. finish build team
2. finish build player_consist_of

In [2]:
import csv
team_name = []
with open('dota2ti7team.csv', 'r') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')
    for row in spamreader:
        rows = row[0].split('\t')
        team_name.append(rows[0])
team_name = team_name[1:]

In [3]:
import pandas as pd

In [4]:
# eliminate player in two teams
dict = {}
players = []
player_in_team = []
new_team = []
position = []
cnt = 0;
for idx,name in enumerate(team_name):
    if (os.path.exists('useteam/' + name + '.csv')):
        df = pd.read_csv('useteam/' + name + '.csv')
        player = df.Player[1:6].tolist()
        new_team.append(name)
        dict[name] = []
        position_cnt = 0;
        for p in player:
            cnt = 6
            while (p in players):
                p = df.Player[cnt]
                cnt += 1
            dict[name].append(p)
            players.append(p)
            # add idx of the team
            player_in_team.append(len(new_team))
            # add position
            position.append(position_cnt % 5 + 1)
            position_cnt += 1

In [5]:
len(new_team)

16

In [6]:
# see if there is duplciates
dupl = []
for (idx1,p1) in enumerate(players):
    for (idx2, p2) in enumerate(players):
        if (p1 == p2 and idx1 != idx2):
            dupl.append(p1)

In [7]:
pd_consist_of = pd.DataFrame({'player_id': range(1, 81), 
                            'player_position': position,
                            'player_team_id' : player_in_team,
                            'player_name': players})

In [8]:
dict

{'Alliance': ['Akke', 'AdmiralBulldog', 'Handsken', 'EGM', 'Pajkatt'],
 'CDECGaming': ['Q', 'Agressif', 'June', 'Flyby', 'demons'],
 'Cloud9': ['bOne7', 'MiSeRy', 'Aui_2000', 'FATA-', 'SingSing'],
 'EHOME': ['old chicken', 'old eLeVeN', 'CTY', 'END', 'Fenrir'],
 'Fnatic': ['Trixi', 'DJ', 'Era', 'n0tail', 'Ohaiyo'],
 'InvictusGaming': ['ChuaN', 'Faith', 'Xi', 'BurNIng', 'Boboka.Rr'],
 'LGDForeverYoung': ['Monet', 'LPC', 'ddc', 'ah fu', 'Inflame'],
 'LGDGAMING': ['Maybe', 'MMY!', 'xiao8', 'Sylar', 'OB.DD'],
 'NatusVincere': ['XBOCT', 'Funn1k', 'Puppey', 'GeneRaL', 'SoNNeikO'],
 'Newbee': ['kaka', 'kpii', 'Hao', 'banana', 'Newbee.SanSheng'],
 'OG': ['Fly', 'JerAx', 'Miracle', 'MoonMeander', 'Cr1t-'],
 'TeamEmpire': ['Resolut1on',
  'ALWAYSWANNAFLY',
  'Scandal',
  'ALOHADANCE',
  'VANSKOR'],
 'TeamLiquid': ['TC', 'KuroKy', 'MATUMBAMAN', 'MinD_ContRoL', 'FLUFFNSTUFF'],
 'TeamSecret': ['pieliedie', 'MidOne', 'Arteezy', 's4', 'MP'],
 'ViciGaming': ['hym', 'Super', 'rOtk', 'iceiceice', 'Yang'],
 'Virtuspro': ['G', 'Lil', 'COK', 'Fng', 'DkPhobos']}

In [9]:
pd_consist_of

    player_id      player_name  player_position  player_team_id
0           1               TC                1               1
1           2           KuroKy                2               1
2           3       MATUMBAMAN                3               1
3           4     MinD_ContRoL                4               1
4           5      FLUFFNSTUFF                5               1
5           6            Monet                1               2
6           7              LPC                2               2
7           8              ddc                3               2
8           9            ah fu                4               2
9          10          Inflame                5               2
10         11            Maybe                1               3
11         12             MMY!                2               3
12         13            xiao8                3               3
13         14            Sylar                4               3
14         15            OB.DD                5               3
15         16             kaka                1               4
16         17             kpii                2               4
17         18              Hao                3               4
18         19           banana                4               4
19         20  Newbee.SanSheng                5               4
20         21       Resolut1on                1               5
21         22   ALWAYSWANNAFLY                2               5
22         23          Scandal                3               5
23         24       ALOHADANCE                4               5
24         25          VANSKOR                5               5
25         26        pieliedie                1               6
26         27           MidOne                2               6
27         28          Arteezy                3               6
28         29               s4                4               6
29         30               MP                5               6
..        ...              ...              ...             ...
50         51                Q                1              11
51         52         Agressif                2              11
52         53             June                3              11
53         54            Flyby                4              11
54         55           demons                5              11
55         56      old chicken                1              12
56         57       old eLeVeN                2              12
57         58              CTY                3              12
58         59              END                4              12
59         60           Fenrir                5              12
60         61            Trixi                1              13
61         62               DJ                2              13
62         63              Era                3              13
63         64           n0tail                4              13
64         65           Ohaiyo                5              13
65         66              hym                1              14
66         67            Super                2              14
67         68             rOtk                3              14
68         69        iceiceice                4              14
69         70             Yang                5              14
70         71            bOne7                1              15
71         72           MiSeRy                2              15
72         73         Aui_2000                3              15
73         74            FATA-                4              15
74         75         SingSing                5              15
75         76             Akke                1              16
76         77   AdmiralBulldog                2              16
77         78         Handsken                3              16
78         79              EGM                4              16
79         80          Pajkatt                5              16

[80 rows x 4 columns]

In [10]:
pd_consist_of.to_csv('output/player_consist_of.csv', encoding='utf-8', index=False, header=False)

In [11]:
pd_team = pd.DataFrame(new_team)
pd_team.index += 1
pd_team.to_csv('output/pro_team.csv', encoding='utf-8', index=True, header=False)

In [12]:
pd_player_consist_of = pd.DataFrame()

# make participate.csv

In [13]:
Ti_league = {}
for i in range(2, 7):
    Ti_league[str(i)] = []
    team_name_append = []
    with open('../ti' + str(i) +'/201' + str(i) + '.csv', 'r') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=' ', quotechar='|')
        for row in spamreader:
            rows = row[0].split('\t')
            team_name_append.append(rows[0])
        team_name_append = team_name_append[1:]
        for name in team_name_append:
            if name in new_team:
                Ti_league[str(i)].append(name)
Ti_league[str(7)] = new_team

In [14]:
# make a dictionary
Ti_league

{'2': ['LGDGAMING', 'InvictusGaming', 'NatusVincere', 'EHOME'],
 '3': ['Alliance',
  'NatusVincere',
  'Fnatic',
  'InvictusGaming',
  'LGDGAMING',
  'TeamLiquid',
  'Virtuspro'],
 '4': ['ViciGaming',
  'Newbee',
  'LGDGAMING',
  'TeamLiquid',
  'Virtuspro',
  'InvictusGaming',
  'Cloud9',
  'CDECGaming',
  'NatusVincere',
  'Alliance',
  'Fnatic',
  'TeamEmpire'],
 '5': ['LGDGAMING',
  'CDECGaming',
  'EHOME',
  'TeamSecret',
  'ViciGaming',
  'Virtuspro',
  'NatusVincere',
  'TeamEmpire',
  'Newbee',
  'InvictusGaming',
  'Cloud9',
  'Alliance',
  'Fnatic'],
 '6': ['EHOME',
  'Fnatic',
  'OG',
  'Alliance',
  'ViciGaming',
  'TeamSecret',
  'Newbee',
  'InvictusGaming',
  'TeamEmpire',
  'Virtuspro',
  'TeamLiquid',
  'NatusVincere',
  'LGDGAMING',
  'CDECGaming'],
 '7': ['TeamLiquid',
  'LGDForeverYoung',
  'LGDGAMING',
  'Newbee',
  'TeamEmpire',
  'TeamSecret',
  'OG',
  'Virtuspro',
  'NatusVincere',
  'InvictusGaming',
  'CDECGaming',
  'EHOME',
  'Fnatic',
  'ViciGaming',
  'Cloud9',
  'Alliance']}

In [15]:
for key in Ti_league:
    print(key + "  " + str(len(Ti_league[key])))

2  4
3  7
4  12
5  13
6  14
7  16

In [16]:
league_id = []
team_id = []
for key in Ti_league:
    for v in Ti_league[key]:
        league_id.append(int(key))
        team_id.append(new_team.index(v) + 1)

In [17]:
df_participate = pd.DataFrame({ 'league_id': league_id, 
                                'team_id': team_id
                            })

In [18]:
df_participate.to_csv('output/participate.csv', encoding='utf-8', index=False, header=False)

# make Heros.csv

In [19]:
import json
try:
    import urllib.request as urllib2
except ImportError:
    import urllib2
# open the url and the screen name 
# (The screen name is the screen name of the user for whom to return results for)
url = "https://api.opendota.com/api/heroes"
# this takes a python object and dumps it to a string which is a JSON
# representation of that object
data = json.load(urllib2.urlopen(url))
# print the result
# print (data)
data[34]

{'attack_type': 'Ranged',
 'id': 36,
 'legs': 2,
 'localized_name': 'Necrophos',
 'name': 'npc_dota_hero_necrolyte',
 'primary_attr': 'int',
 'roles': ['Carry', 'Nuker', 'Durable', 'Disabler']}

In [20]:
pd_hero = pd.DataFrame(data)

In [21]:
pd_hero = pd_hero.drop(['legs', 'name', 'primary_attr'], axis = 1)

In [22]:
pd_hero = pd_hero[['id', 'localized_name', 'attack_type', 'roles']]

In [23]:
pd_hero.to_csv('output/hero.csv', encoding='utf-8', index=False, header=False)

# make items.csv

In [24]:
import numpy as np

In [25]:
df_item = pd.read_csv('Items.csv')

In [26]:
df_item

,Item,# Purchases,Fastest (secs),Slowest (secs),Mean (secs),Std Deviation,Winrate
0,Town Portal Scroll,28164,-38,4756,1118,636,47.24%
1,Observer Ward,10853,-88,4626,1192,759,49.89%
2,Sentry Ward,10662,-87,4541,1395,679,47.65%
3,Observer and Sentry Wards,10357,-88,4626,1405,692,48.77%
4,Clarity,6642,-89,4644,808,630,53.70%
5,Iron Branch,4866,-89,3704,609,514,50.78%
6,Smoke of Deceit,3629,-89,4399,1120,697,49.46%
7,Boots of Speed,3468,-89,4470,349,559,51.07%
8,Magic Stick,3026,-88,3225,375,299,50.46%
9,Magic Wand,2662,-88,3225,517,362,50.45%
10,Enchanted Mango,2426,-89,4047,559,473,50.95%
11,Circlet,2130,-89,4501,646,559,54.08%
12,Sage's Mask,2102,-76,3765,852,657,53.66%
13,Infused Raindrops,2100,180,3128,584,364,49.62%
14,Tome of Knowledge,2042,600,4398,1399,700,50.34%
15,Ring of Health,2031,165,4363,1514,688,57.21%
16,Wind Lace,1951,-85,3668,820,564,52.64%
17,Staff of Wizardry,1950,325,4596,1482,581,54.92%
18,Ring of Regen,1938,-81,3704,847,577,54.54%
19,Healing Salve,1903,-89,3888,527,874,46.35%
20,Ogre Axe,1792,434,4741,1532,586,53.96%
21,Gloves of Haste,1702,103,4068,725,516,50.06%
22,Blades of Attack,1627,66,3858,568,538,50.28%
23,Ring of Protection,1386,-86,3693,601,481,53.61%
24,Void Stone,1370,298,4364,1612,745,57.45%
25,Mithril Hammer,1350,414,4741,1592,562,54.44%
26,Belt of Strength,1314,98,4258,768,553,52.21%
27,Blink Dagger,1269,430,3427,1222,456,54.06%
28,Gauntlets of Strength,1244,-85,2806,555,387,54.34%
29,Band of Elvenskin,1154,46,3930,1078,430,52.60%
...,...,...,...,...,...,...,...
172,Heaven's Halberd,56,998,3083,1893,512,57.14%
173,Necronomicon,55,762,1833,1173,240,47.27%
174,Aeon Disk,54,1333,3950,2248,667,62.96%
175,Heart of Tarrasque,51,1141,3687,2154,556,78.43%
176,Recipe: Refresher Orb,50,1879,4364,2981,656,62.00%
177,Recipe: Bloodthorn,50,1714,3858,2614,537,70.00%
178,Refresher Orb,50,1915,4364,2993,647,62.00%
179,Bloodthorn,50,1755,3863,2629,536,70.00%
180,Rod of Atos,48,661,2629,1384,437,62.50%
181,Recipe: Abyssal Blade,48,1551,3362,2074,385,81.25%
182,Recipe: Rod of Atos,48,646,2624,1349,438,62.50%
183,Abyssal Blade,47,1608,3369,2112,374,82.98%
184,Dagon,46,1324,4503,2210,652,60.87%
185,Octarine Core,45,1191,3700,2266,600,77.78%
186,Boots of Travel,40,2262,4486,3149,586,65.00%
187,Moon Shard,40,1500,4168,2944,579,72.50%
188,Nullifier,40,1492,3695,2308,530,62.50%
189,Recipe: Crimson Guard,38,1146,3584,1891,485,65.79%
190,Satanic,36,1909,3396,2496,402,69.44%
191,Crimson Guard,35,1147,2949,1904,417,65.71%
192,Helm of the Dominator,32,419,2072,882,353,40.62%
193,Dagon,32,1397,4506,2136,596,56.25%
194,Recipe: Daedalus,28,1504,3613,2395,528,64.29%
195,Dagon,25,1492,4642,2304,596,60.00%
196,Meteor Hammer,25,652,2564,1476,525,84.00%
197,Daedalus,24,1538,3748,2448,556,62.50%
198,Dagon,22,1552,4753,2443,633,59.09%
199,Animal Courier,19,-88,-67,-83,5,42.11%
200,Divine Rapier,18,2033,4045,2975,686,16.67%
201,Ethereal Blade,17,1382,3274,2198,626,58.82%

In [27]:
price = np.array(df_item['Mean (secs)'].tolist(), dtype = int)
price = price - price % 100
price[price <= 0] = 50

In [28]:
len(price)

202

In [29]:
df_item['price'] = price * 2

In [30]:
df_item = df_item.drop(['# Purchases', 'Fastest (secs)', 'Slowest (secs)', 'Mean (secs)', 'Std Deviation', 'Winrate'], axis = 1)

In [31]:
df_item.index += 1
df_item.to_csv('output/item.csv', encoding='utf-8', index=True, header=False)

# make match.csv

In [32]:
import random
import time
random.seed(100)

In [33]:
Ti_league

{'2': ['LGDGAMING', 'InvictusGaming', 'NatusVincere', 'EHOME'],
 '3': ['Alliance',
  'NatusVincere',
  'Fnatic',
  'InvictusGaming',
  'LGDGAMING',
  'TeamLiquid',
  'Virtuspro'],
 '4': ['ViciGaming',
  'Newbee',
  'LGDGAMING',
  'TeamLiquid',
  'Virtuspro',
  'InvictusGaming',
  'Cloud9',
  'CDECGaming',
  'NatusVincere',
  'Alliance',
  'Fnatic',
  'TeamEmpire'],
 '5': ['LGDGAMING',
  'CDECGaming',
  'EHOME',
  'TeamSecret',
  'ViciGaming',
  'Virtuspro',
  'NatusVincere',
  'TeamEmpire',
  'Newbee',
  'InvictusGaming',
  'Cloud9',
  'Alliance',
  'Fnatic'],
 '6': ['EHOME',
  'Fnatic',
  'OG',
  'Alliance',
  'ViciGaming',
  'TeamSecret',
  'Newbee',
  'InvictusGaming',
  'TeamEmpire',
  'Virtuspro',
  'TeamLiquid',
  'NatusVincere',
  'LGDGAMING',
  'CDECGaming'],
 '7': ['TeamLiquid',
  'LGDForeverYoung',
  'LGDGAMING',
  'Newbee',
  'TeamEmpire',
  'TeamSecret',
  'OG',
  'Virtuspro',
  'NatusVincere',
  'InvictusGaming',
  'CDECGaming',
  'EHOME',
  'Fnatic',
  'ViciGaming',
  'Cloud9',
  'Alliance']}

In [34]:
for key in Ti_league:
    print(key + " " +str(len(Ti_league[key])))

2 4
3 7
4 12
5 13
6 14
7 16

In [35]:
a21 = (2011,8,1,0,0,0,0,0,0)
a22 = (2012,7,6,23,59,59,0,0,0)
a31 = (2012,8,1,0,0,0,0,0,0)
a32 = (2013,7,6,23,59,59,0,0,0)
a41 = (2013,8,1,0,0,0,0,0,0)
a42 = (2014,7,6,23,59,59,0,0,0)
a51 = (2014,8,1,0,0,0,0,0,0)
a52 = (2015,7,6,23,59,59,0,0,0)
a61 = (2015,8,1,0,0,0,0,0,0)
a62 = (2016,7,6,23,59,59,0,0,0)
a71 = (2016,8,1,0,0,0,0,0,0)
a72 = (2017,7,6,23,59,59,0,0,0)
A1 = [a21, a31, a41, a51, a61, a71]
A2 = [a22, a32, a42, a52, a62, a72]

In [36]:
date = []
tm = []
Match = []
league = []

In [37]:
match_count = [0, 0, 18, 81, 213, 369, 551, 791]

In [38]:
for i in range(2, 8):
    start=time.mktime(A1[i - 2])
    end=time.mktime(A2[i - 2])
    for j in range(match_count[i - 1] + 1, match_count[i] + 1):
        t=random.randint(start, end)
        date_touple=time.localtime(t)
        date.append(time.strftime("%Y-%m-%d",date_touple))
        tm.append(time.strftime("%H:%M:%S", date_touple))
        Match.append(j)
        league.append(i)

In [39]:
len(Match)

791

In [40]:
df_match = pd.DataFrame({'Match' : Match,
                         'league' : league,
                         'date': date,
                         'tm' : tm
                        })

In [41]:
df_match.to_csv('output/match_host.csv', encoding='utf-8', index = False, header=False)

# make team_compose.csv

In [42]:
random.seed(100)

In [43]:
tc_compose = []
tc_radiant = []
tc_fb = []
tc_win = []
tc_tower = []
for i in Match:
    fb_rd = random.randint(0, 1)
    win_rd = random.randint(0, 1)
    tc_compose.append(i)
    tc_radiant.append(0)
    tc_fb.append(fb_rd)
    tc_win.append(win_rd)
    tc_tower.append(random.randint(0, 11))
    
    tc_compose.append(i)
    tc_radiant.append(1)
    tc_fb.append(fb_rd ^ 1)
    tc_win.append(win_rd ^ 1)
    tc_tower.append(random.randint(0, 11))

In [44]:
df_tc = pd.DataFrame({'tc_compose' : tc_compose,
                         'tc_radiant' : tc_radiant,
                         'tc_fb': tc_fb,
                         'tc_win' : tc_win,
                          'tc_tower' : tc_tower
                        })

In [45]:
df_tc = df_tc[['tc_compose', 'tc_radiant', 'tc_fb', 'tc_win', 'tc_tower']]

In [46]:
df_tc

      tc_compose  tc_radiant  tc_fb  tc_win  tc_tower
0              1           0      0       1         7
1              1           1      1       0         2
2              2           0      1       1         6
3              2           1      0       0         8
4              3           0      0       0         1
5              3           1      1       1        11
6              4           0      1       1         0
7              4           1      0       0        10
8              5           0      0       1         3
9              5           1      1       0         4
10             6           0      0       0         2
11             6           1      1       1         3
12             7           0      1       1        10
13             7           1      0       0         6
14             8           0      0       1         7
15             8           1      1       0         8
16             9           0      1       1         2
17             9           1      0       0        10
18            10           0      0       0         0
19            10           1      1       1         9
20            11           0      1       0         9
21            11           1      0       1         2
22            12           0      0       0         0
23            12           1      1       1        10
24            13           0      0       1        10
25            13           1      1       0         6
26            14           0      0       0         9
27            14           1      1       1         3
28            15           0      1       1         8
29            15           1      0       0        10
...          ...         ...    ...     ...       ...
1552         777           0      1       0        10
1553         777           1      0       1         3
1554         778           0      1       0         4
1555         778           1      0       1        11
1556         779           0      1       0         5
1557         779           1      0       1         9
1558         780           0      0       1         0
1559         780           1      1       0         0
1560         781           0      0       1         9
1561         781           1      1       0         7
1562         782           0      0       0         2
1563         782           1      1       1         6
1564         783           0      0       1         0
1565         783           1      1       0        10
1566         784           0      0       0        11
1567         784           1      1       1         3
1568         785           0      0       1         3
1569         785           1      1       0         1
1570         786           0      0       0         4
1571         786           1      1       1         8
1572         787           0      1       1         6
1573         787           1      0       0         8
1574         788           0      1       1         7
1575         788           1      0       0         7
1576         789           0      0       1         4
1577         789           1      1       0         9
1578         790           0      0       0         7
1579         790           1      1       1         2
1580         791           0      0       1         3
1581         791           1      1       0         6

[1582 rows x 5 columns]

In [47]:
df_tc.to_csv('output/team_compose.csv', encoding='utf-8', index = False, header=False)

# make Play_In

In [68]:
random.seed(100)

In [69]:
Ti_league

{'2': ['LGDGAMING', 'InvictusGaming', 'NatusVincere', 'EHOME'],
 '3': ['Alliance',
  'NatusVincere',
  'Fnatic',
  'InvictusGaming',
  'LGDGAMING',
  'TeamLiquid',
  'Virtuspro'],
 '4': ['ViciGaming',
  'Newbee',
  'LGDGAMING',
  'TeamLiquid',
  'Virtuspro',
  'InvictusGaming',
  'Cloud9',
  'CDECGaming',
  'NatusVincere',
  'Alliance',
  'Fnatic',
  'TeamEmpire'],
 '5': ['LGDGAMING',
  'CDECGaming',
  'EHOME',
  'TeamSecret',
  'ViciGaming',
  'Virtuspro',
  'NatusVincere',
  'TeamEmpire',
  'Newbee',
  'InvictusGaming',
  'Cloud9',
  'Alliance',
  'Fnatic'],
 '6': ['EHOME',
  'Fnatic',
  'OG',
  'Alliance',
  'ViciGaming',
  'TeamSecret',
  'Newbee',
  'InvictusGaming',
  'TeamEmpire',
  'Virtuspro',
  'TeamLiquid',
  'NatusVincere',
  'LGDGAMING',
  'CDECGaming'],
 '7': ['TeamLiquid',
  'LGDForeverYoung',
  'LGDGAMING',
  'Newbee',
  'TeamEmpire',
  'TeamSecret',
  'OG',
  'Virtuspro',
  'NatusVincere',
  'InvictusGaming',
  'CDECGaming',
  'EHOME',
  'Fnatic',
  'ViciGaming',
  'Cloud9',
  'Alliance']}

In [70]:
a = Ti_league['2']
a
# len(Ti_league[str(league_number)])

['LGDGAMING', 'InvictusGaming', 'NatusVincere', 'EHOME']

In [71]:
pi_compose = []
pi_radiant = []
pi_team = []
for i in Match:
    league_number = 0;
    if (i >= 1 and i <=18):
        league_number = 2
    elif i <= 81:
        league_number = 3
    elif i <= 213:
        league_number = 4
    elif i <= 369:
        league_number = 5
    elif i <= 551:
        league_number = 6
    elif i <= 791:
        league_number = 7
    length = len(Ti_league[str(league_number)])
    rd1 = 0
    rd2 = 0
    while rd1 == rd2:
        rd1 = random.randint(0, length - 1)
        rd2 = random.randint(0, length - 1)
    pi_compose.append(i)
    pi_radiant.append(0)
    pi_team.append(new_team.index(Ti_league[str(league_number)][rd1]))
    
    pi_compose.append(i)
    pi_radiant.append(1)
    pi_team.append(new_team.index(Ti_league[str(league_number)][rd2]))

In [72]:
df_Play_In = pd.DataFrame({'pi_compose' : pi_compose,
                           'pi_radiant' : pi_radiant,
                           'pi_team' : pi_team
                            })

In [73]:
df_Play_In

      pi_compose  pi_radiant  pi_team
0              1           0        9
1              1           1       11
2              2           0       11
3              2           1        9
4              3           0       11
5              3           1        8
6              4           0       11
7              4           1        2
8              5           0       11
9              5           1        8
10             6           0        2
11             6           1        9
12             7           0        8
13             7           1        9
14             8           0        8
15             8           1        9
16             9           0        9
17             9           1        8
18            10           0        8
19            10           1       11
20            11           0        9
21            11           1       11
22            12           0       11
23            12           1        8
24            13           0       11
25            13           1        9
26            14           0        2
27            14           1        9
28            15           0        2
29            15           1       11
...          ...         ...      ...
1552         777           0       15
1553         777           1        7
1554         778           0        3
1555         778           1        0
1556         779           0       14
1557         779           1        9
1558         780           0        1
1559         780           1       12
1560         781           0       10
1561         781           1        2
1562         782           0        5
1563         782           1        7
1564         783           0       13
1565         783           1       15
1566         784           0       11
1567         784           1        7
1568         785           0        3
1569         785           1       13
1570         786           0       11
1571         786           1       14
1572         787           0        1
1573         787           1       12
1574         788           0        3
1575         788           1       10
1576         789           0        6
1577         789           1       10
1578         790           0       15
1579         790           1        1
1580         791           0       10
1581         791           1        8

[1582 rows x 3 columns]

In [74]:
df_Play_In.to_csv('output/play_in.csv', encoding='utf-8', index = False, header=False)

# make Hero_belong_to

In [75]:
random.seed(100)

In [89]:
random.randint(0,1)

1

In [85]:
random.sample(range(1, 120), 1)

[1]

In [ ]:
hbt_compose = []
hbt_radiant = []
hbt_hero = []
for i in Match: